.TH "Easy Apache" 1
.SH NAME
easy-apache \- script to easily setup apache server and install ssl certificate(s)
.SH SYNOPSIS
.B easy-apache
[OPTIONS]
.SH DESCRIPTION
.PP
Easy Apache is a simple script that helps you setup an Apache server, configure it completely, and it also helps you in installing SSL certificates for all your Apache sites. It'll ask for a few inputs, like domain name, do you want to install SSL, etc that's it.
.PP
It takes care of configuring Apache, setting up virtual hosts (vhosts), managing different directories for each site, enabling site, disabling sites, and even installing an SSL certificate to your Apache sites.
.SH OPTIONS
.TP
.BR \-s ", " \-\-ssl
Setup domain with SSL certificates
.TP
.BR \-h ", " \-\-help
Help (shows available commands)
.TP
.BR \-v ", " \-\-version
Check easy-apache version
.SH EXAMPLES
.TP
.BR easy-apache " " \-s example.com 
Setup domain with ssl certificates
.SH AUTHORS
.PP
(C) Copyright 2020 R Pavan Kumar <realpvn@gmail.com>
.PP
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH BUGS
Report bugs on the github repo for easy-apache (https://github.com/realpvn/easy-apache.git). Open a issue and I will reply/fix as soon as I can.
.SH CONTRIBUTE
.PP
You can contribute to Easy Apache here - https://github.com/realpvn/easy-apache.git. If your contributions are good/big your name might be added to AUTHORS section