name: easy-apache
base: core20
version: '2.11'
summary: Easy Apache is a script to get an apache server up and running
description: |
  It'll ask you some questions like domain name if you want to install SSL (Yes or No questions) etc
  other than that it does most of the things like configuring apache, setting up virtual host,
  managing different directories for each site, enabling site, disabling default sites applying an SSL certificate to the domain only you specify.
  
  If you have any questions or issues, please do let me know on GitHub repository (https://github.com/realpvn/easy-apache/)
grade: stable
confinement: strict

parts:
  easy-apache:
    plugin: dump
    source: .
    stage-packages:
      - curl
      - apache2

apps:
  easy-apache:
    command: easy-apache.sh
    plugs:
      - network